// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.Api.Migrations.Identity
{
    /// <inheritdoc />
    public partial class Rename_AllIdentityTableName : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 先拿掉 refresh_tokens -> aps_net_users 的外鍵
            migrationBuilder.DropForeignKey(
                name: "fk_refresh_tokens_users_user_id",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.DropForeignKey(
                name: "fk_aps_net_role_claims_aps_net_roles_role_id",
                schema: "identity",
                table: "aps_net_role_claims");

            migrationBuilder.DropForeignKey(
                name: "fk_aps_net_user_claims_aps_net_users_user_id",
                schema: "identity",
                table: "aps_net_user_claims");

            migrationBuilder.DropForeignKey(
                name: "fk_aps_net_user_logins_aps_net_users_user_id",
                schema: "identity",
                table: "aps_net_user_logins");

            migrationBuilder.DropForeignKey(
                name: "fk_aps_net_user_roles_aps_net_roles_role_id",
                schema: "identity",
                table: "aps_net_user_roles");

            migrationBuilder.DropForeignKey(
                name: "fk_aps_net_user_roles_aps_net_users_user_id",
                schema: "identity",
                table: "aps_net_user_roles");

            migrationBuilder.DropForeignKey(
                name: "fk_aps_net_user_tokens_aps_net_users_user_id",
                schema: "identity",
                table: "aps_net_user_tokens");

            migrationBuilder.DropPrimaryKey(
                name: "pk_aps_net_users",
                schema: "identity",
                table: "aps_net_users");

            migrationBuilder.DropPrimaryKey(
                name: "pk_aps_net_user_tokens",
                schema: "identity",
                table: "aps_net_user_tokens");

            migrationBuilder.DropPrimaryKey(
                name: "pk_aps_net_user_roles",
                schema: "identity",
                table: "aps_net_user_roles");

            migrationBuilder.DropPrimaryKey(
                name: "pk_aps_net_user_logins",
                schema: "identity",
                table: "aps_net_user_logins");

            migrationBuilder.DropPrimaryKey(
                name: "pk_aps_net_user_claims",
                schema: "identity",
                table: "aps_net_user_claims");

            migrationBuilder.DropPrimaryKey(
                name: "pk_aps_net_roles",
                schema: "identity",
                table: "aps_net_roles");

            migrationBuilder.DropPrimaryKey(
                name: "pk_aps_net_role_claims",
                schema: "identity",
                table: "aps_net_role_claims");

            migrationBuilder.RenameTable(
                name: "aps_net_users",
                schema: "identity",
                newName: "asp_net_users",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "aps_net_user_tokens",
                schema: "identity",
                newName: "asp_net_user_tokens",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "aps_net_user_roles",
                schema: "identity",
                newName: "asp_net_user_roles",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "aps_net_user_logins",
                schema: "identity",
                newName: "asp_net_user_logins",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "aps_net_user_claims",
                schema: "identity",
                newName: "asp_net_user_claims",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "aps_net_roles",
                schema: "identity",
                newName: "asp_net_roles",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "aps_net_role_claims",
                schema: "identity",
                newName: "asp_net_role_claims",
                newSchema: "identity");

            migrationBuilder.RenameIndex(
                name: "ix_aps_net_user_roles_role_id",
                schema: "identity",
                table: "asp_net_user_roles",
                newName: "ix_asp_net_user_roles_role_id");

            migrationBuilder.RenameIndex(
                name: "ix_aps_net_user_logins_user_id",
                schema: "identity",
                table: "asp_net_user_logins",
                newName: "ix_asp_net_user_logins_user_id");

            migrationBuilder.RenameIndex(
                name: "ix_aps_net_user_claims_user_id",
                schema: "identity",
                table: "asp_net_user_claims",
                newName: "ix_asp_net_user_claims_user_id");

            migrationBuilder.RenameIndex(
                name: "ix_aps_net_role_claims_role_id",
                schema: "identity",
                table: "asp_net_role_claims",
                newName: "ix_asp_net_role_claims_role_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_asp_net_users",
                schema: "identity",
                table: "asp_net_users",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_asp_net_user_tokens",
                schema: "identity",
                table: "asp_net_user_tokens",
                columns: new[] { "user_id", "login_provider", "name" });

            migrationBuilder.AddPrimaryKey(
                name: "pk_asp_net_user_roles",
                schema: "identity",
                table: "asp_net_user_roles",
                columns: new[] { "user_id", "role_id" });

            migrationBuilder.AddPrimaryKey(
                name: "pk_asp_net_user_logins",
                schema: "identity",
                table: "asp_net_user_logins",
                columns: new[] { "login_provider", "provider_key" });

            migrationBuilder.AddPrimaryKey(
                name: "pk_asp_net_user_claims",
                schema: "identity",
                table: "asp_net_user_claims",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_asp_net_roles",
                schema: "identity",
                table: "asp_net_roles",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_asp_net_role_claims",
                schema: "identity",
                table: "asp_net_role_claims",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_asp_net_role_claims_asp_net_roles_role_id",
                schema: "identity",
                table: "asp_net_role_claims",
                column: "role_id",
                principalSchema: "identity",
                principalTable: "asp_net_roles",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_asp_net_user_claims_asp_net_users_user_id",
                schema: "identity",
                table: "asp_net_user_claims",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "asp_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_asp_net_user_logins_asp_net_users_user_id",
                schema: "identity",
                table: "asp_net_user_logins",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "asp_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_asp_net_user_roles_asp_net_roles_role_id",
                schema: "identity",
                table: "asp_net_user_roles",
                column: "role_id",
                principalSchema: "identity",
                principalTable: "asp_net_roles",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_asp_net_user_roles_asp_net_users_user_id",
                schema: "identity",
                table: "asp_net_user_roles",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "asp_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_asp_net_user_tokens_asp_net_users_user_id",
                schema: "identity",
                table: "asp_net_user_tokens",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "asp_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
            
            // 補回 refresh_tokens -> asp_net_users
            migrationBuilder.AddForeignKey(
                name: "fk_refresh_tokens_users_user_id",
                schema: "identity",
                table: "refresh_tokens",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "asp_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // 先拿掉 refresh_tokens -> asp_net_users
            migrationBuilder.DropForeignKey(
                name: "fk_refresh_tokens_users_user_id",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.DropForeignKey(
                name: "fk_asp_net_role_claims_asp_net_roles_role_id",
                schema: "identity",
                table: "asp_net_role_claims");

            migrationBuilder.DropForeignKey(
                name: "fk_asp_net_user_claims_asp_net_users_user_id",
                schema: "identity",
                table: "asp_net_user_claims");

            migrationBuilder.DropForeignKey(
                name: "fk_asp_net_user_logins_asp_net_users_user_id",
                schema: "identity",
                table: "asp_net_user_logins");

            migrationBuilder.DropForeignKey(
                name: "fk_asp_net_user_roles_asp_net_roles_role_id",
                schema: "identity",
                table: "asp_net_user_roles");

            migrationBuilder.DropForeignKey(
                name: "fk_asp_net_user_roles_asp_net_users_user_id",
                schema: "identity",
                table: "asp_net_user_roles");

            migrationBuilder.DropForeignKey(
                name: "fk_asp_net_user_tokens_asp_net_users_user_id",
                schema: "identity",
                table: "asp_net_user_tokens");

            migrationBuilder.DropPrimaryKey(
                name: "pk_asp_net_users",
                schema: "identity",
                table: "asp_net_users");

            migrationBuilder.DropPrimaryKey(
                name: "pk_asp_net_user_tokens",
                schema: "identity",
                table: "asp_net_user_tokens");

            migrationBuilder.DropPrimaryKey(
                name: "pk_asp_net_user_roles",
                schema: "identity",
                table: "asp_net_user_roles");

            migrationBuilder.DropPrimaryKey(
                name: "pk_asp_net_user_logins",
                schema: "identity",
                table: "asp_net_user_logins");

            migrationBuilder.DropPrimaryKey(
                name: "pk_asp_net_user_claims",
                schema: "identity",
                table: "asp_net_user_claims");

            migrationBuilder.DropPrimaryKey(
                name: "pk_asp_net_roles",
                schema: "identity",
                table: "asp_net_roles");

            migrationBuilder.DropPrimaryKey(
                name: "pk_asp_net_role_claims",
                schema: "identity",
                table: "asp_net_role_claims");

            migrationBuilder.RenameTable(
                name: "asp_net_users",
                schema: "identity",
                newName: "aps_net_users",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_tokens",
                schema: "identity",
                newName: "aps_net_user_tokens",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_roles",
                schema: "identity",
                newName: "aps_net_user_roles",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_logins",
                schema: "identity",
                newName: "aps_net_user_logins",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_claims",
                schema: "identity",
                newName: "aps_net_user_claims",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_roles",
                schema: "identity",
                newName: "aps_net_roles",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_role_claims",
                schema: "identity",
                newName: "aps_net_role_claims",
                newSchema: "identity");

            migrationBuilder.RenameIndex(
                name: "ix_asp_net_user_roles_role_id",
                schema: "identity",
                table: "aps_net_user_roles",
                newName: "ix_aps_net_user_roles_role_id");

            migrationBuilder.RenameIndex(
                name: "ix_asp_net_user_logins_user_id",
                schema: "identity",
                table: "aps_net_user_logins",
                newName: "ix_aps_net_user_logins_user_id");

            migrationBuilder.RenameIndex(
                name: "ix_asp_net_user_claims_user_id",
                schema: "identity",
                table: "aps_net_user_claims",
                newName: "ix_aps_net_user_claims_user_id");

            migrationBuilder.RenameIndex(
                name: "ix_asp_net_role_claims_role_id",
                schema: "identity",
                table: "aps_net_role_claims",
                newName: "ix_aps_net_role_claims_role_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_aps_net_users",
                schema: "identity",
                table: "aps_net_users",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_aps_net_user_tokens",
                schema: "identity",
                table: "aps_net_user_tokens",
                columns: new[] { "user_id", "login_provider", "name" });

            migrationBuilder.AddPrimaryKey(
                name: "pk_aps_net_user_roles",
                schema: "identity",
                table: "aps_net_user_roles",
                columns: new[] { "user_id", "role_id" });

            migrationBuilder.AddPrimaryKey(
                name: "pk_aps_net_user_logins",
                schema: "identity",
                table: "aps_net_user_logins",
                columns: new[] { "login_provider", "provider_key" });

            migrationBuilder.AddPrimaryKey(
                name: "pk_aps_net_user_claims",
                schema: "identity",
                table: "aps_net_user_claims",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_aps_net_roles",
                schema: "identity",
                table: "aps_net_roles",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_aps_net_role_claims",
                schema: "identity",
                table: "aps_net_role_claims",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_aps_net_role_claims_aps_net_roles_role_id",
                schema: "identity",
                table: "aps_net_role_claims",
                column: "role_id",
                principalSchema: "identity",
                principalTable: "aps_net_roles",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_aps_net_user_claims_aps_net_users_user_id",
                schema: "identity",
                table: "aps_net_user_claims",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "aps_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_aps_net_user_logins_aps_net_users_user_id",
                schema: "identity",
                table: "aps_net_user_logins",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "aps_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_aps_net_user_roles_aps_net_roles_role_id",
                schema: "identity",
                table: "aps_net_user_roles",
                column: "role_id",
                principalSchema: "identity",
                principalTable: "aps_net_roles",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_aps_net_user_roles_aps_net_users_user_id",
                schema: "identity",
                table: "aps_net_user_roles",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "aps_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_aps_net_user_tokens_aps_net_users_user_id",
                schema: "identity",
                table: "aps_net_user_tokens",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "aps_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
            
            // 補回 refresh_tokens -> aps_net_users
            migrationBuilder.AddForeignKey(
                name: "fk_refresh_tokens_users_user_id",
                schema: "identity",
                table: "refresh_tokens",
                column: "user_id",
                principalSchema: "identity",
                principalTable: "aps_net_users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
