name: Client CI

on:
  workflow_dispatch:
  push:
    paths:
      - "client/devhabit-ui/**"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client/devhabit-ui

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "client/devhabit-ui/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          VITE_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          VITE_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}

      - name: Install SWA CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy
        run: swa deploy --env production --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
